#!/bin/bash

sudo apt-get install build-essential libgl1-mesa-dev
pip install --user --index-url=http://download.qt.io/snapshots/ci/pyside/5.9/latest/ pyside2 --trusted-host download.qt.io

python3 setup.py sdist
python3 setup.py install --user